version: '3.7'

services:
  react-easy-peasy-ts:
    image: react-easy-peasy-ts
    ports:
      - 5999:5999
    container_name: 'react-easy-peasy-ts'
    restart: unless-stopped
    volumes:
      - ../build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
